apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-status-api-deployment
  labels:
    app: plant-status-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-status-api
  template:
    metadata:
      labels:
        app: plant-status-api
    spec:
      containers:
        - name: plant-status-api
          image: europewest1-docker.pkg.dev/home-sensor-hub/container-repository/plant-status-api
          ports:
            - containerPort: 8080