name: Deploy Process Sensor Telemetry Function

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/588483809961/locations/global/workloadIdentityPools/github2/providers/github-provider'
          service_account: 'github@home-sensor-hub.iam.gserviceaccount.com'

      - name: action-zip
        uses: montudor/action-zip@v1.0.0
        with:
            args: zip -qq -r process-sensor-telemetry.zip process-sensor-telemetry/*
      
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'process-sensor-telemetry.zip'
          destination: 'function_artifacts'
