name: Deploy Process Sensor Telemetry Function

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/588483809961/locations/global/workloadIdentityPools/github2/providers/github-provider'
          service_account: 'github@home-sensor-hub.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'process-sensor-telemetry'
          runtime: 'go116'
          entrypoint: 'ProcessTelemetry'
          memory_mb: 128
          source_dir: 'process-sensor-telemetry'
          event_trigger_type: 'providers/cloud.pubsub/eventTypes/topic.publish'
          event_trigger_resource: 'telemetry'

